### ISSUE TITLE
The link to the repo is broken when the package was registered with its SSH url

### ISSUE THREAD

**Issue by stof** [Jleagle/php-packages.com#3]
See http://packages.jimeagle.com/package/asgard/console for such a link on the `Repo` button.

there is 2 things you should do:
- fix links to github repos, [as done by Packagist](https://github.com/composer/packagist/blob/743e3f228b32c2e1eab01840db96be2dc54dd809/src/Packagist/WebBundle/Resources/views/Web/viewPackage.html.twig#L107) as the way to create links is known here
- prefer the link to the source available in the `support` section of the package over the repo url when it is provided, as it is the way for packages to give the url of their source viewer when it is different than the repo url (which can happen often given that one is for an HTML page showing the repo content and the other one is for git access)

**Comment by Jleagle** [comment]
I converted the repo URL into a text field as it shouldn't have been a link in the first place.
I checked a few repos for the support field but couldn't find one with it filled in. I also don't store this value in the database yet, but I will at some point then i can favour this field over others.

**Comment by stof** [comment]
@Jleagle Github repos generally don't bother about setting it, especially for the source url, given that the same URL can be used to clone the repo and view the source, and that Composer is also able to guess the url to view a given branch as it knows the github pattern. It would be important for repos hosted elsewhere.

If you want a package using it explicitly rather than relying on the composer guessing, have a look at https://packagist.org/packages/smarty/smarty

**Comment by Jleagle** [comment]
Thanks for the info, it was only a form and email field where I copied it from the bootstrap page, fixed now, will push later.
